name: my_water
description: "Water Bill Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP
  dio: ^5.4.0

  # State management
  provider: ^6.1.1

  # Secure storage for JWT
  flutter_secure_storage: ^9.0.0

  # QR / Barcode scanning & generation
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0

  # UI & Animations
  google_fonts: ^6.1.0
  fl_chart: ^0.66.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
